### ISSUE TITLE
Enable basic configuration of UI and indexing via config file

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#185]
Possible things to be configured:
- Tokenizer, see https://github.com/skohub-io/skohub-vocabs/issues/153#issuecomment-1104890725
- ~~Reconcile server (see also discussion in SkoHub chat from 2022-04-01)~~
- ~~Not relevant at the moment but when ActivityPub features are re-enabled: Enable inboxes, configure ActivityPub server to be used...~~

Questions:
- Should the config be made per repo or per vocab?
- What should the file look like? YAML?

**Comment by sroertgen** [comment]
> Questions:
> 
> Should the config be mad per repo or per vocab?

Since a skohub-vocabs instance might host multiple vocabs I guess it makes sense to define this per vocab or give something like a default config if nothing is specified for a specific vocab. This might make implementation a little bit more difficult, but seems sensible.

> What should the file look like? YAML?

I would actually favour TOML (https://toml.io/en/) over YAML, because it is easier to write and read for humans (easy for machines as well).

**Comment by sroertgen** [comment]
So to summarize the following options should be configurable:

tokenizer: see options https://github.com/nextapps-de/flexsearch/tree/0.6.32#tokenizer
ui:
  - colors
  - logo

@acka47 Do you want the fonts to be configurable as well or are colors and logo sufficent?

**Comment by acka47** [comment]
> Do you want the fonts to be configurable as well or are colors and logo sufficent?

Why not? As far as I can see, the only instance that customized the design (for test purposes) also adjusted the fonts: http://zpidvokabulare.surge.sh/index.de.html
