### ISSUE TITLE
Show ScopeNote in nwbib.ttl notations 102000, 102060

### ISSUE THREAD

**Issue by HMetzner** [skohub-io/skohub-vocabs#266]
All notations show ScopeNote accordingly except the ones [102000 Landesbeschreibungen](https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.de.html#N102000) and [102060 Reiseberichte](https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.de.html#N102060).

**Comment by acka47** [comment]
Adding some context: This issue is about the NWBib subject classification which uses hash URIs. A build can be viewed at https://test.skohub.io/hbz/lobid-vocabs/heads/master/purl.org/lobid/rpb.de.html.

I have added links to the mentioned concepts in the original comment. By now everything seems fine as the scopeNote is shown. So it must have been some problem in the vocabulary that is fixed by now. Right, @HMetzner ? Please close the issue if you agree.
