### ISSUE TITLE
Need for even deeper hierarchy level

### ISSUE THREAD

**Issue by LasseMempel** [skohub-io/skohub-vocabs#309]
The thesaurus I am working with has two deeper hierarchy levels than currently supported.
Any chance there is space for these? Or to avoid future issues of the same type a limitless (to a certain degree) nesting support?

**Comment by acka47** [comment]
Thanks for the request, @LasseMempel. This is similar to #156 where we already added support for additional hierarchies.

**Comment by sroertgen** [comment]
Hey @LasseMempel ,

limitless is difficult due to the fact that graphql does not support recursion. But two more levels should be no problem.

@acka47 so should we just add two more levels?

Maybe at some point in the future we can think about restructuring the graphql queries to allow limitless levels

**Comment by LasseMempel** [comment]
Two more levels would be a nice start ;)

**Comment by acka47** [comment]
> @acka47 so should we just add two more levels?

+1

**Comment by sroertgen** [comment]
@LasseMempel sorry for the delay. I was on parental leave and did not open my laptop too much.

I added two more levels on branch https://github.com/skohub-io/skohub-vocabs/tree/309-deeper-hierarchy and opened #311

**Comment by LasseMempel** [comment]
No worries, I'm glad to hear you're investing in your family!
